OK
NURx2/HashTable pull request #1
Opened 2019-03-25 20:38 UTC by NURx2

2019-03-28 22:56 UTC, ifsmirnov requested changes

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +};
Пустая строка в конце файла.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +    void stopTheWorld() {
Ну серьёзно? И как я должен догадаться, что тут происходит? Стражей Галактики позвать на помощь?

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +    size_t bigSize;  // includes removed elements, need for stopTheWorld
Непонятен смысл названий. Нужно назвать так, чтобы был понятен.

Использовать cur в названии плохо. Если возникает коллизия с названием метода size(), можно использовать какой-нибудь стиль для именования полей, например, data_, used_, ...

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        std::vector<std::pair<KeyType, ValueType>> ndata(newSize);
Тогда уж newData, newUsed, newRemoved. А ещё newRemoved не нужен.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +    HashMap(const std::initializer_list<std::pair<KeyType, ValueType>> & il,
initializer_list можно по значению.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +     friend class HashMap;  // когда нулы
К чему комментарий?

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        size_t i;
Никаких однобуквенных переменных. HashMap* owner, size_t elementIndex.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        size_t next(size_t x) {
Опять же, хочу нормальное название для x.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        iterator(HashMap * a = 0, size_t x = 0) : p(a) {
explicit, нормальные названия параметров. Имей в виду, что название аргуменов констуктора может совпадать с названием поля класса, это легально.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +            return reinterpret_cast<const std::pair<const KeyType, ValueType>&>(
Ты умеешь объяснять, почему reinterpret_cast тут легален?

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        size_t pos = mustBe(key);
Копипаст. Нужно сделать отдельную функцию, ищущую элемент, а в find вызывать её и создавать итератор нужного типа.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        for (size_t i = 0; i < data.size(); ++i) {
index

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        size_t pos = mustBe(key);
И тут копипаст.

2019-03-28 22:56 UTC, ifsmirnov commented on HashMap.h
> +        size_t pos = mustBe(key);
И тут. Нужна функция, допустим, size_t locateElement(const KeyType& key).

2019-03-29 19:37 UTC, NURx2 commented on HashMap.h
> +    HashMap(const std::initializer_list<std::pair<KeyType, ValueType>> & il,
А почему, в чем смысл?

2019-04-14 16:40 UTC, merged